// <auto-generated />
using System;
using Gorevcim.Repository.AppDbContexts.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gorevcim.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221214120047_merve")]
    partial class merve
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gorevcim.Core.Models.BranchOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyType")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyWebUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InvoiceMailAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TaxAdministration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("BranchOffice");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ofis Ürünleri"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Polen Haşere"
                        },
                        new
                        {
                            Id = 3,
                            Name = "İzolasyon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İnşaat"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Montaj Asma"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tadilat"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tamir"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Maskeleme"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kaydırmaz"
                        },
                        new
                        {
                            Id = 10,
                            Name = "İç Cephe Boyalar"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Dış Cephe Boyalar"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tinerler"
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CompanyType")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyWebUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InvoiceMailAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TaxAdministration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.CompanyDealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyType")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyWebUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("InvoiceMailAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TaxAdministration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyDealer");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductBrands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BrandsName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BrandsWebUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("LogoBase64Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandsName = "BBBBb",
                            BrandsWebUrl = "AAAA",
                            Explanation = "dfgvgrfg",
                            ShortCode = "sddsad"
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductColors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ColorBase64Content")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ColorFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ColorFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sarı"
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductCurrencyUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductFeaturesId")
                        .HasColumnType("int");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductCurrencyUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Explanation = "dfgvgrfg",
                            Name = "BBBBb",
                            ProductFeaturesId = 0,
                            ShortCode = "AAAA"
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("int");

                    b.Property<int>("ProductCurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductImageId")
                        .HasColumnType("int");

                    b.Property<int>("ProductMeasurementId")
                        .HasColumnType("int");

                    b.Property<int>("ProductProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProductVatId")
                        .HasColumnType("int");

                    b.Property<int>("ProductWeightId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductCurrencyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductImageId");

                    b.HasIndex("ProductMeasurementId");

                    b.HasIndex("ProductProjectId");

                    b.HasIndex("ProductVatId");

                    b.HasIndex("ProductWeightId");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Base64Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductMeasurementUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductMeasurementUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "XXX",
                            ShortCode = "xx"
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductProjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aaa"
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExplanationWebUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<int>("IsMixture")
                        .HasColumnType("int");

                    b.Property<string>("LogoBase64Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LogoFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PurchasePrice")
                        .HasColumnType("int");

                    b.Property<int?>("SalePrice")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalWebUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "AS123",
                            CategoryId = 1,
                            Code = "123AS",
                            CreateDate = new DateTime(2022, 12, 14, 15, 0, 46, 761, DateTimeKind.Local).AddTicks(9069),
                            ExpirationDate = new DateTime(2022, 12, 14, 15, 0, 46, 761, DateTimeKind.Local).AddTicks(9061),
                            Explanation = "hghghggh",
                            ExplanationWebUrl = "dlld",
                            IsMixture = 0,
                            LogoBase64Content = "ad",
                            LogoFileName = "sdf",
                            LogoFilePath = "sdsdf",
                            Name = "Test Ürün1",
                            PurchasePrice = 10,
                            SalePrice = 15,
                            Stock = 1,
                            TechnicalWebUrl = "dfsd",
                            UpdateDate = new DateTime(2022, 12, 14, 15, 0, 46, 761, DateTimeKind.Local).AddTicks(9070)
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductVatUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductVatUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1",
                            Name = "XXX"
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductWeightUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("ActiveDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsActiveDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsActiveDateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDelete")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IsDeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IsDeleteDateUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IsDeleteDateUpdateUserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsDeleteDateUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductWeightUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "XXX",
                            ShortCode = "X1"
                        });
                });

            modelBuilder.Entity("Gorevcim.Core.Models.BranchOffice", b =>
                {
                    b.HasOne("Gorevcim.Core.Models.Company", "Company")
                        .WithMany("BranchOffice")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.CompanyDealer", b =>
                {
                    b.HasOne("Gorevcim.Core.Models.Company", "Company")
                        .WithMany("CompanyDealer")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductFeatures", b =>
                {
                    b.HasOne("Gorevcim.Core.Models.ProductColors", "ProductColors")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ColorId");

                    b.HasOne("Gorevcim.Core.Models.ProductBrands", "ProductBrands")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductBrandId");

                    b.HasOne("Gorevcim.Core.Models.ProductCurrencyUnits", "ProductCurrencyUnits")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductCurrencyId");

                    b.HasOne("Gorevcim.Core.Models.Products", "Products")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductId");

                    b.HasOne("Gorevcim.Core.Models.ProductImage", "ProductImage")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductImageId");

                    b.HasOne("Gorevcim.Core.Models.ProductMeasurementUnits", "ProductMeasurementUnits")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductMeasurementId");

                    b.HasOne("Gorevcim.Core.Models.ProductProjects", "ProductProjects")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductProjectId");

                    b.HasOne("Gorevcim.Core.Models.ProductVatUnits", "ProductVatUnits")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductVatId");

                    b.HasOne("Gorevcim.Core.Models.ProductWeightUnits", "ProductWeightUnits")
                        .WithMany("ProductFeatures")
                        .HasForeignKey("ProductWeightId");

                    b.Navigation("ProductBrands");

                    b.Navigation("ProductColors");

                    b.Navigation("ProductCurrencyUnits");

                    b.Navigation("ProductImage");

                    b.Navigation("ProductMeasurementUnits");

                    b.Navigation("ProductProjects");

                    b.Navigation("ProductVatUnits");

                    b.Navigation("ProductWeightUnits");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.Products", b =>
                {
                    b.HasOne("Gorevcim.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.Company", b =>
                {
                    b.Navigation("BranchOffice");

                    b.Navigation("CompanyDealer");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductBrands", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductColors", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductCurrencyUnits", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductImage", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductMeasurementUnits", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductProjects", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.Products", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductVatUnits", b =>
                {
                    b.Navigation("ProductFeatures");
                });

            modelBuilder.Entity("Gorevcim.Core.Models.ProductWeightUnits", b =>
                {
                    b.Navigation("ProductFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
